local opt = vim.opt -- for conciseness

opt.autoindent = true -- copy indent from current line when starting new one
opt.background = "dark" -- colorschemes that can be light or dark will be made dark
opt.backspace = "indent,eol,start" -- allow backspace on indent, end of line or insert mode start position
opt.breakindent = true
opt.clipboard:append("unnamedplus") -- use system clipboard as default register
opt.cmdheight = 0
opt.completeopt = "menuone,noselect"
opt.conceallevel = 0
opt.confirm = true
opt.cursorline = true -- highlight the current cursor line
opt.expandtab = true -- expand tab to spaces
opt.fillchars = [[eob: ,fold: ,foldopen:,foldsep: ,foldclose:]]
opt.foldcolumn = "1" -- '0' is not bad
opt.foldenable = true
opt.foldlevel = 99 -- Using ufo provider need a large value, feel free to decrease the value
opt.foldlevelstart = 99
opt.formatoptions = "jqlnt" -- tcqj
opt.hidden = true
opt.hlsearch = false
opt.ignorecase = true -- ignore case when searching
opt.inccommand = "nosplit"
opt.joinspaces = false
opt.laststatus = 3 -- global statusline
opt.list = true
opt.mouse = "a"
opt.number = true -- shows absolute line number on cursor line (when relative number is on)
opt.pumblend = 10
opt.pumheight = 10
opt.relativenumber = true -- show relative line numbers
opt.scrollback = 100000
opt.scrolloff = 8
opt.sessionoptions = { "buffers", "curdir", "tabpages", "winsize" }
opt.shiftround = true
opt.shiftwidth = 2 -- 2 spaces for indent width
opt.shortmess:append { W = true, I = true, c = true, C = true }
opt.showcmd = false
opt.showmode = false
opt.sidescrolloff = 8
opt.signcolumn = "yes" -- show sign column so that text doesn't shift
opt.smartcase = true -- if you include mixed case in your search, assumes you want case-sensitive
opt.smartindent = true
opt.splitbelow = true -- split horizontal window to the bottom
opt.splitkeep = "screen"
opt.splitright = true -- split vertical window to the right
opt.swapfile = false -- turn off swapfile
opt.tabstop = 2 -- 2 spaces for tabs (prettier default)
opt.termguicolors = true -- turn on termguicolors for nightfly colorscheme to work
opt.timeoutlen = 300
opt.title = true
opt.undofile = true
opt.updatetime = 200
opt.wildmode = "longest:full,full"
opt.wrap = false -- disable line wrapping

vim.g.mapleader = " "
vim.g.maplocalleader = ","
vim.g.markdown_recommended_style = 0
vim.keymap.set({ "n", "v" }, "<Space>", "<Nop>", { silent = true })